### PR TITLE
[DRAFT] Don't record swapchain images setup while replaying+recording

### PR DESCRIPTION
**Pull request by panos-lunarg**
Experimental

### CODE REVIEW

**Comment by panos-lunarg** [comment]
Sorry forgot to create this as a draft so I added a note in the title

**Comment by bradgrantham-lunarg** [comment]
Great, Panos, thank you!

I assume the generated code changes would be added to the generators if this moved forward.

It might be nice to know what happens with these getprocaddrs if other layers are active upchain of the GFXR layer during replay.  That is to say, if 

Also any other app could getprocaddr and call these functions, right?  If GFXR becomes more widespread but game developers want to forcibly disable capturing in their app, I think they might call these functions.  Could this functionality be more abstract, like a way for replay to note to capture that it is beginning and ending a replay state snapshot (trimmed range state setup) command, and then the capture layer can recreate the kBeginMarker and kEndMarker that are in the source capture in the new capture?  Then a subsequent replay can know to not screenshot during state snapshot replay.

**Comment by panos-lunarg** [comment]
> It might be nice to know what happens with these getprocaddrs if other layers are active upchain of the GFXR capture layer during replay. That is to say, if VVL is between replay and the capture layer.

Good question. I haven't thought of that. Need to check.

>I think if recording is just disabled/re-enabled by gfxrecon-replay, then information is doubly lost. Won't the recaptured capture's first Acquire expect a different index?

From what I understand/have seen from the runs I did locally, `SetSwapchainImageStateCommand` is only called when replaying a trimmed capture. This is done in order to set the state of the swapchain images in such a manner that is in agreement with the state at of the images on the first captured frame. If the replay is re-captured again then I guess that information does not matter since:
- If capturing un-trimmed then swapchain images start from scratch.
- If capturing trimmed then a new `SetSwapchainImageStateCommandHeader` will be recorded.
So I think we don't lose any information that needs to be preserved in the new capture. These are all guesses/thoughts on my side so feel free to straighten me out in case I am wrong.

**Comment by bradgrantham-lunarg** [comment]
> > I think if recording is just disabled/re-enabled by gfxrecon-replay, then information is doubly lost. Won't the recaptured capture's first Acquire expect a different index?
> 
> From what I understand/have seen from the runs I did locally, `SetSwapchainImageStateCommand` is only called when replaying a trimmed capture. This is done in order to set the state of the swapchain images in such a manner that is in agreement with the state at of the images on the first captured frame. If the replay is re-captured again then I guess that information does not need to be recapruted since:
> 
> * If capturing un-trimmed then swapchain images start from scratch.
> * If capturing trimmed then a new `SetSwapchainImageStateCommandHeader` will be created and recorded from the layer.

When replay processes `SetSwapchainImageStateCommandHeader`, if all the images can't be acquired up front (https://github.com/LunarG/gfxreconstruct/blob/6bf1a6a89a80ef7e490f0b9ca4259d8386e1da21/framework/decode/vulkan_replay_consumer_base.cpp#L720), the replay issues the initial `Present`s to get to the correct swapchain index.  In current `dev` applied, on some platforms that becomes unexpected black/junk initial images in replay of the recapture but at the end of the initial images the swapchain index will be set correctly.  That's the whole point of this PR if I understand it correctly.

But with this PR applied the **replay of the recapture** won't make those initial image `Present`s *and* the swapchain index won't be set correctly.  I think this will be true for both trimmed and un-trimmed recapture.  I talked this through with David and we're pretty sure as well as not recording the `Present` calls a recapture will need to correctly reset the swapchain index.  So when replay calls `StopRecording`, the capture layer will need to set a flag to package up and write a new `SetSwapchainImageStateCommand` when `ResumeRecording` is called.

**Comment by bradgrantham-lunarg** [comment]
I think `virtual-swapchain` handles this.  What do you think?

**Comment by bradgrantham-lunarg** [comment]
@panos-lunarg I think `virtual-swapchain` handles this.  What do you think?

**Comment by panos-lunarg** [comment]
Yeah, sounds good

**Pull request closed without merging**
