### PR TITLE
Fix accounting for a thread's shared lock state

### PR DESCRIPTION
**Pull request by panos-lunarg**
Change-Id: I7e9bfc77ddcd3f972468e59a38779dd5523f9412

### CODE REVIEW

**Comment by panos-lunarg** [comment]
I'm afraid that this patch needs some work. I just run into an assertion failure in https://github.com/LunarG/gfxreconstruct/pull/910/files#diff-86d287f9befc06931be97da47215184aaf84c64f41e94d12893623de00d5e833R36

**Comment by ishitatsuyuki** [comment]
I can test this later but as noted in review this misses one of the point mentioned in #910. There's also the question whether we should retain the upgrading functionality at all (also mentioned in review comment).

**Comment by ishitatsuyuki** [comment]
Just had the time to check MSVC's shared_mutex implementation and it seems at least recent versions use SRWLOCK, which should not require kernel roundtrip unless contended.

It might be interesting to redo the performance test David has done [here](https://github.com/LunarG/gfxreconstruct/issues/909#issuecomment-1322585920) and check if it's still worth rolling our own sync primitive.

**Comment by davidd-lunarg** [comment]
@ishitatsuyuki Thanks for looking into this. Using `std::shared_mutex` appears to have similar capture-time performance as the internal `SharedMutex` implementation. I'll look into switching GFXR to use it.

**Comment by davidd-lunarg** [comment]
#979 changes GFXR to use `std::shared_mutex`. Once that is merged I will close this PR.

**Pull request closed without merging**
