### PR TITLE
Fix for unhandled page guard segmentation fault

### PR DESCRIPTION
**Pull request by panos-lunarg**
On some very rare occasions on arm64 the address that caused the
segmentation fault on a page guarded memory region is not store in
info->si_addr but in the platform dependent ucontext_t struct.

This patch addresses this issue by always deducing the faulty address by
reading the ucontext_t struct when executing on arm64

### CODE REVIEW

**Comment by bradgrantham-lunarg** [comment]
I actually think `ucontext_t` may be the better place to get this information.  Tempted to merge this PR.

**Comment by panos-lunarg** [comment]
Really not sure about that. Haven't seen this triggering before nor after the Fortnite investigation

**Comment by bradgrantham-lunarg** [comment]
@panos-lunarg This PR Is a quite old.  Should we close this as not relevant or should we merge it?

**Comment by panos-lunarg** [comment]
We can close this. I have no intention of merging it

**Pull request closed without merging**
