### PR TITLE
Check return value of GetRayTracingCaptureReplayShaderGroupHandlesKHR [WIP]

### PR DESCRIPTION
**Pull request by charles-lunarg**
Would appreciate being given direction on whether the error handling is appropriate - the error code will be propagated upwards which may cause the application to fail (due to exiting on any error). It may also cause replay to fail because the error code for this command won't be VK_SUCCESS.

### CODE REVIEW

**Comment by bradgrantham-lunarg** [comment]
I think we generally fail if the call succeeded in capture and fails in replay.  I think calling `CheckResult` is appropriate.

**Review by bradgrantham-lunarg — APPROVED** [review]

**Comment by bradgrantham-lunarg** [comment]
This PR failed internal CI because it caused recapture of the raytracing captures to fail.  But they were actually failing silently, so a change to CI to represent this PR is appropriate.

**Comment by bradgrantham-lunarg** [comment]
Once the clang-format issue reported by the GitHub Actions CI build is resolved ("CI Build / Ubuntu GCC Release") then please merge this PR.

**Comment by charles-lunarg** [comment]
I'm going to re-run the tests just to be sure it wasn't a fluke (and that the current CI works with this change)

**Pull request merged**
