### PR TITLE
exit with 0 if capture wasn't optimizable

### PR DESCRIPTION
**Pull request by bradgrantham-lunarg**

### CODE REVIEW

**Review by charles-lunarg — APPROVED** [review]
Only nit is that I prefer giving member variables in classes default values (like false) rather than using an initializer list in a constructor, but that's not something to fix in this PR - just stating my preference.

Gave it a spin on my local machine and didn't see any cause for concern.

**Comment by charles-lunarg** [comment]
If there was any PR to squash into a single commit, its this one due to the need to fix formatting issues.

**Comment by bradgrantham-lunarg** [comment]
> Only nit is that I prefer giving member variables in classes default values (like false) rather than using an initializer list in a constructor, but that's not something to fix in this PR - just stating my preference.
> 
> Gave it a spin on my local machine and didn't see any cause for concern.

I agree but I decided to match the existing style, which I think is important.

**Comment by bradgrantham-lunarg** [comment]
> If there was any PR to squash into a single commit, its this one due to the need to fix formatting issues.

omg clang-format

**Pull request merged**
