### PR TITLE
Declared default for setting.

### PR DESCRIPTION
**Pull request by andrew-lunarg**
Trivial doc fix.

### CODE REVIEW

**Review by panos-lunarg — DISMISSED** [review]
Same information exists on USAGE_android.md

**Comment by andrew-lunarg** [comment]
> 



> Same information exists on USAGE_android.md

Thanks, fixed now.

**Review by hiddenbitious — APPROVED** [review]

**Review by panos-lunarg — APPROVED** [review]

**Comment by panos-lunarg** [comment]
Sorry that was my personal account

**Comment by andrew-lunarg** [comment]
I noticed. Still managed to approve though!

**Pull request merged**
