### PR TITLE
Add macOS to github-release-build action

### PR DESCRIPTION
**Pull request by fabian-lunarg**

### CODE REVIEW

**Comment by bradgrantham-lunarg** [comment]
Did this get tested by doing a release on a separate fork or anything like that?

**Comment by fabian-lunarg** [comment]
> Did this get tested by doing a release on a separate fork or anything like that?

not yet. I was looking for a manual trigger to test the action, but that seems not defined.
from what I see, the action is only run when pushing into a tag-branch:

```
on:
  push:
    tags:
      - v*
```

should I add a manual trigger for testing (and remove that afterwards) or is there another way to invoke the action?

**Comment by bradgrantham-lunarg** [comment]
> > Did this get tested by doing a release on a separate fork or anything like that?
> 
> not yet. I was looking for a manual trigger to test the action, but that seems not defined. from what I see, the action is only run when pushing into a tag-branch:
> 
> ```
> on:
>   push:
>     tags:
>       - v*
> ```
> 
> should I add a manual trigger for testing (and remove that afterwards) or is there another way to invoke the action?

I think if you brought your `dev` on your fork of this repo or a separate temporary testing forked repo up to date with this branch, you could push a `v*` tag to that repo and that would start the "release" action and you'd see the results in Releases on that fork.

You can delete the release from the forked repo afterwards.  If you change `dev` on your personal development fork you can just force-push your `dev` back to matching the main `dev` after that.

You can see in my personal development fork that I've done that in the past and just was sloppy about deleting the releases: https://github.com/bradgrantham-lunarg/gfxreconstruct/releases

**Comment by fabian-lunarg** [comment]
looking good:
 https://github.com/fabian-lunarg/gfxreconstruct/actions/runs/10280694169

@bradgrantham-lunarg

**Review by charles-lunarg — APPROVED** [review]
Seems good to me! (and the proof is in the CI job, so thats easy to check if its 'correct')

**Pull request merged**
