### PR TITLE
Fix a crash on replay for trimmed trace

### PR DESCRIPTION
**Pull request by naomipappe**
When the descriptor sets are updated using `vkUpdateDescriptorSetWithTemplate` in the captured application, and the update in question involves updating acceleration structures, the trimmed trace would crash on replay.

This is caused by the fact that state recreation uses `vkUpdateDescriptorSets` and `VkWriteDescriptorSet`, which requires the information for the update of acceleration structures be chained in the `pNext` field of relevant `VkWriteDescriptorSet` with `VkWriteDescriptorSetAccelerationStructureKHR` structure filled appropriately. As the `vkUpdateDescriptorSetWithTemplate` does not share this structure, the `pNext` ends up empty on state recreation, and thus causes a crash.

This change fixes that, by filling out the required structure and copying it.

This change also depends on #1363 to properly copy the structure data.

### CODE REVIEW

**Comment by bradgrantham-lunarg** [comment]
I think if you make your branch for this PR to be the #1363 branch plus these changes, then CI won't fail because of missing functions, and after #1363 is merged the commits in this PR that are also in #1363's branch will not be duplicated when this PR is merged.

**Comment by lunarpapillo** [comment]
The LunarG CI failure appears to be due to an unrelated GPU crash. I've restored the machine and will restart the test.

**Comment by MarkY-LunarG** [comment]
I wrote a test to verify this fix in [my fork of Sascha Willem's examples](https://github.com/MarkY-LunarG/Vulkan/tree/marky_move_raytrace_reflect_to_desc_templates).  I'm also going to create a separate issue to not use the pnext chains like we are (as you mentioned) but to eventually fix this correctly.

**Comment by MarkY-LunarG** [comment]
Rebased on dev (now that #1363 was integrated it through this into chaos.

**Pull request merged**
