### PR TITLE
Add wait before present option

### PR DESCRIPTION
**Pull request by bartosz-muszarski-arm**
Force wait on completion of queue operations for all queues before calling Present. This is needed for accurate acquisition of instrumentation data on some platforms.

### CODE REVIEW

**Review by andrew-lunarg — APPROVED** [review]
Looks like a nice, tight little change.

Only question I have is whether it needs to account for alternate frame delimiters for platforms where images get to eyeballs without going through presents. Doing so could be a later edition though if it doesn't matter for the platforms the author cares about / is able to test on easily.

**Comment by bartosz-muszarski-arm** [comment]
> Looks like a nice, tight little change.
> 
> Only question I have is whether it needs to account for alternate frame delimiters for platforms where images get to eyeballs without going through presents. Doing so could be a later addition though if it doesn't matter for the platforms the author cares about / is able to test on easily.

We can add this later, as you said it's not something we can test easily now

**Comment by bradgrantham-lunarg** [comment]
> We can add this later, as you said it's not something we can test easily now

Can you test this against https://github.com/LunarG/gfxreconstruct/pull/1138?

**Review by charles-lunarg — APPROVED** [review]
The contents of the PR needed rebasing/cleanup to work with current dev. I did have to redo how the device handle was used to get the dispatch table to make it function. 

The design is reasonable - force a vkDeviceWaitIdle on every vkQueuePresentKHR.

**Pull request merged**
