### PR TITLE
Base change set to resolve dev <-> openxr_experimental inconsistencies

### PR DESCRIPTION
**Pull request by jzulauf-lunarg**
* Rename Vulkan Info objects and accessors
Other API's may have device, instance, swapchain objects, so qualify Vulkan state with Vulkan or Vk

### CODE REVIEW

**Comment by jzulauf-lunarg** [comment]
Setting as draft as this is the first of several commits that will be needed to resolve the openxr-experimental branch drift

**Review by MarkY-LunarG — APPROVED** [review]
LGTM

**Comment by bradgrantham-lunarg** [comment]
Is this still WIP or should I add it to my review queue?

**Comment by bradgrantham-lunarg** [comment]
I took a chance on rebasing this on current target branch because I did a `rebase` locally and the diffs minus the `dev` revisions before and after appeared the same except for line numbers.

**Comment by jzulauf-lunarg** [comment]
@bradgrantham-lunarg -- i noticed somebody rebased my branch... but I didn't check what was done to it, and just pushed the most recent with a rebase on dev as of 4pm Wed MDT.  

This should be ready for review, already dealing with merge conflict, so getting this in soon as we're happy with it would be good.

**Comment by jzulauf-lunarg** [comment]
There are formatting fixes to do where CI and Windows have a disagreement.

**Comment by jzulauf-lunarg** [comment]
@bradgrantham-lunarg  @davidd-lunarg  -- clean now.  Subject to easy disturbance from dev... would like to fast track this.

**Comment by jzulauf-lunarg** [comment]
Ongoing pushes to stay up-to-date with dev.

**Review by bradgrantham-lunarg — APPROVED** [review]
Please file issues for any warts that you know you want to go back and address.

**Pull request merged**
