### PR TITLE
Updated empty generated UnwrapStructHandles() in .cpp file to inline functions in header

### PR DESCRIPTION
**Pull request by David-J-Tinley**
Removed the empty generated functions in `framework\generated\generated_vulkan_struct_handle_wrappers.cpp` and made them into inline functions in the header file at `framework\generated\generated_vulkan_struct_handle_wrappers.hpp ` This was for issue #1199

### CODE REVIEW

**Comment by bradgrantham-lunarg** [comment]
Hi, @David-J-Tinley !  Thanks for your contribution!  Do you have changes to the Python generator scripts that you haven't committed?

**Comment by David-J-Tinley** [comment]
Hi @bradgrantham-lunarg , sorry I completely missed the part in the issue #1199 messages where @andrew-lunarg said to rebuild the generated code with `python3 generate_vulkan.py`. Should I delete this pull request and resubmit another one after the rebuild? Thank you for your time!

**Comment by andrew-lunarg** [comment]
@David-J-Tinley, if you want to keep at this, the task is to edit the python scripts for the C++ header and body that they automatically generate code with the same changes applied that you have made manually. 

You would also want to refresh your fork and then either rebase your branch on dev or just start a new branch since you would be editing different files anyway and your branch currently contains quite a lot of unrelated history.

Thinking some more about the problem it may not have been quite such a good first issue as I had imagined since the header generator would need to duplicate some of the work of the body generator to know whether it should emit a function prototype or an inline empty function in each case and there's a slightly higher level design decision to be made there about duplicating code versus factoring it out.

**Comment by David-J-Tinley** [comment]
@andrew-lunarg oh ok, I think I misunderstood the overall issue but it is starting to make a little more sense. It sounds like it may be a little bit beyond what I could do unfortunately. Would you like me to remove my pull request? Thank you for taking the time to explain things to me though, I appreciate it!

**Comment by andrew-lunarg** [comment]
@David-J-Tinley Sure no problem. Thanks for giving it a shot :).

**Pull request closed without merging**
